### ISSUE TITLE
Issue running the crawler

### ISSUE THREAD

**Issue by albertolina** [spider-rs/spider-nodejs#1]
Hello

I am finding issue in running the example, this is the error I am getting:

thread '<unnamed>' panicked at src/website.rs:770:36:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6

My code:

`
const spider = require("@spider-rs/spider-rs");

const website = new spider.Website('https://www.example.com')
        .withBudget({
            "*": 20,
        })
        .build();

    // optional: page event handler
    const onPageEvent = (_err, page) => {
        const title = spider.pageTitle(page); // comment out to increase performance if title not needed
        console.info(`Title of ${page.url} is '${title}'`);
        website.pushData({
            status: page.statusCode,
            html: page.content,
            url: page.url,
            title,
        });
    };

    await website.crawl(onPageEvent);
    console.log(website.getLinks());`

Can you help me?
Thanks

**Comment by albertolina** [comment]
Reopening this issue because I found whats causing the issue, basically when setting any value different then

`.withBudget({
            '*': 100,
        })`
        
will cause the error I posted above.

if I do this for example:

`        .withBudget({
            '*': 300,
            '/compare': 0
        })`
        
it will crash throwing this error:

`thread '<unnamed>' panicked at src/website.rs:770:36:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6`

Any solution?

**Comment by j-mendez** [comment]
Thanks for the issue @albertolina  the fix will land in `0.0.63`. When you add the budget paths do not add a starting slash for now. Need to look into handling start paths. You can add nested paths like `compare/something`.

**Comment by albertolina** [comment]
Thanks Jeff!

**Comment by albertolina** [comment]
Hey Jeff, just so you know, even if I don't add the starting slash the error happens. I can wait for next version to be released tho. Thanks!

**Comment by j-mendez** [comment]
> Hey Jeff, just so you know, even if I don't add the starting slash the error happens. I can wait for next version to be released tho. Thanks!

Sorry I meant to not add the slash on the next release. It should be available now. Thanks again.
