### ISSUE TITLE
Builds since 0.0,70?

### ISSUE THREAD

**Issue by chreds** [spider-rs/spider-nodejs#2]
I noticed the repo is on 0.0.75 but there haven't been any builds tagged since 0.0.70. Do you plan on resuming the builds? Thanks!

**Comment by chreds** [comment]
I've got the build process figured out, and turns out my google cloud arm machine doesn't even have a binary in your distribution anyways so I'd have to build manually anyways. So if you could add the spider-rs.linux-arm64-gnu.node binaries to your release that would be even better :).

**Comment by chreds** [comment]
Nevermind now about the arm build. I thought it would have better performance, which it probably would, but chromiumoxide won't detect the local chromium for some reason (crawlSmart just fails and doesn't throw an error). Chrome isn't available for arm64. I'll just switch back to x64. So I guess the original question about tagging the builds still stands. 

Thanks.

**Comment by j-mendez** [comment]
@chreds trying to do a deploy now, it takes a long time on the free github action. You could use https://github.com/a11ywatch/chrome to launch chrome over an api and connect to the instance. 

Pulling the `chromiumoxide` crate into the box and fixing the install paths for the OS could be done too.

**Comment by chreds** [comment]
Thanks Jeff. That's helpful, I'll give that a try. Is there any way to enable some debug info on the chrome connection? I tried running a chromium headless build in another docker with 9222 devtools open but the crawlSmart would just fail silently. I tried compiling with yarn build:debug and still there wasn't any feedback. I've actually got it working now in arm64 with chromium installed in the same docker (so not using CHROME_URL).

**Comment by j-mendez** [comment]
> Thanks Jeff. That's helpful, I'll give that a try. Is there any way to enable some debug info on the chrome connection? I tried running a chromium headless build in another docker with 9222 devtools open but the crawlSmart would just fail silently. I tried compiling with yarn build:debug and still there wasn't any feedback. I've actually got it working now in arm64 with chromium installed in the same docker (so not using CHROME_URL).

I think there might be a log enabled setting the RUST_LOG to target the crate or package feature. Napi-rs updated the CI setup, we need to re-configure the CI to deploy. I have not had time to get to this yet.

**Comment by omarkhatibco** [comment]
Hey @j-mendez, thanks for the amazing project,

I don't have rust experience but maybe I could try fixing the CI issue, would that help you?

**Comment by j-mendez** [comment]
> Hey @j-mendez, thanks for the amazing project,
> 
> 
> 
> I don't have rust experience but maybe I could try fixing the CI issue, would that help you?

Hi, yes if you want to take a look at it please be my guest. Our main issue is that we need to install the correct version of "openssl" for each machine. We should comment out all the steps that do not work and one by one fix it could be the best way.

I tried to do most of it at once, and realized some of the matrixes need to be split to have the right openssl type for each OS.

By next week or two I might have time again to try to fix the CI.

**Comment by j-mendez** [comment]
> > Hey @j-mendez, thanks for the amazing project,
> > 
> > 
> > 
> > I don't have rust experience but maybe I could try fixing the CI issue, would that help you?
> 
> Hi, yes if you want to take a look at it please be my guest. Our main issue is that we need to install the correct version of "openssl" for each machine. We should comment out all the steps that do not work and one by one fix it could be the best way.
> 
> I tried to do most of it at once, and realized some of the matrixes need to be split to have the right openssl type for each OS.
> 
> By next week or two I might have time again to try to fix the CI.

There was a point that it did work but, napi-rs changed / broke a step for building on Mac.

**Comment by j-mendez** [comment]
New release 0.0.144 going to make a new issue for FreeBSD support.

**Comment by omarkhatibco** [comment]
Thank you for pushing a new release
