### ISSUE TITLE
Support for wait_for parameter

### ISSUE THREAD

**Issue by gbertb** [spider-rs/spider-nodejs#5]

**Comment by jvmx** [comment]
yes, please enable this - getting inconsistent renders of pages that require javascript

**Comment by j-mendez** [comment]
released in `0.0.148`

**Comment by jvmx** [comment]
Thank you! Is there documentation for how to use it? Trying it out but not 100% what parameters to pass and/or how to use network idle

**Comment by j-mendez** [comment]
> Thank you! Is there documentation for how to use it? Trying it out but not 100% what parameters to pass and/or how to use network idle

Docs pushed - try this: ( first param the seconds to wait, second is the nano seconds ).

```
const website = new Website('https://choosealicense.com').with_wait_for_idle_network(2, 500).build()
```
